### ISSUE TITLE
spryker/ratepay does not work with PHP 7

### ISSUE THREAD

**Issue by stefankleff** [spryker/support#258] opened 2018-12-17 13:28 UTC
This is a

* [ x] bug
* [ ] enhancement

For questions please consult the [Spryker Forum](http://discuss.spryker.com/).

Please provide the exact versions of the modules involved (see composer.lock file).

### What you did
Try to send a RequestPaymentTransaction. 

### Actual Behavior
The Ratepay API responds with HTTP 500 - invalid XML.
```
<ns1:XMLFault xmlns:ns1="http://cxf.apache.org/bindings/xformat"><ns1:faultstring xmlns:ns1="http://cxf.apache.org/bindings/xformat">javax.xml.bind.UnmarshalException\n
 - with linked exception:\n
[com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character '0' (code 48) in content after '&lt;' (malformed start element?).\n
 at [row,col {unknown-source}]: [2,2080]]</ns1:faultstring></ns1:XMLFault>
```

### Expected Behavior
The API accepts the request

### Reason
https://github.com/spryker/ratepay/blob/master/src/Spryker/Zed/Ratepay/Business/Api/Model/AbstractRequest.php#L62 is not working with PHP 7 anymore.

**PHP 5**
```
<?php
$xml = new \SimpleXMLElement('<foo></foo>');
$xml->{0} = 'Bar';
echo (string)$xml->asXML();
```
Output:
```
<?xml version="1.0"?>
<foo>Bar</foo>

```
**PHP 7**
```
<?php
$xml = new \SimpleXMLElement('<foo></foo>');
$xml->{0} = 'Bar';

echo (string)$xml->asXML();
```
Output
```
<?xml version="1.0"?>
<foo><0>Bar</0></foo>
```
Solution:
https://stackoverflow.com/questions/2970575/php-simplexmlelement-set-text

**Comment by tvaleriy** [comment] 2018-12-17 13:44
Thank you for the report. I will notify when it is fixed and released.

**Comment by tvaleriy** [comment] 2019-06-24 11:19
Hi @stefankleff, it seems that the issue isn't relevant because it's about old version of the module.
Newer version has been moved to a separate repository (extracted from the core and moved to the ecosystem). https://github.com/spryker-eco/ratepay/releases.

I'm closing issue. Please don't hesitate to ask further question.

Best,
Spryker Support Team

**Closed by tvaleriy** 2019-06-24 11:19 UTC
Labels: Bug
