### ISSUE TITLE
redirect after login after an Ajax request using a timed out session

### ISSUE THREAD

**Issue by lsmith77** [spryker/support#259] opened 2018-12-17 18:08 UTC
This is a

* [X] bug
* [ ] enhancement

For questions please consult the [Spryker Forum](http://discuss.spryker.com/).

Please provide the exact versions of the modules involved (see composer.lock file).

### What you did

* Open the search page.
* Allow the session to timeout
* Enter a search term (triggering auto suggest but that never finishes)
* Hit enter
* Get redirect to login page
* Login

### Actual Behavior

* Get redirected to the Json response from the auto suggest

### Expected Behavior

* Get redirected to the search result page with the entered search term

**Comment by tvaleriy** [comment] 2019-01-07 14:53
Hi @lsmith77, I can't reproduce described behavior using latest master of our codebase.
And we don't have this redirect thingy by default - user just gets logged out and search results are loaded for a guest in this case.
Can you confirm that it still happens for you?

**Comment by tvaleriy** [comment] 2019-01-07 14:54
Thank you for the report. I will notify when it is fixed and released.

**Comment by tvaleriy** [comment] 2019-07-01 12:14
Hi Lukas, I have to close this ticket as no one of our developers is able to reproduce this anymore.

Best,
Spryker Support Team

**Closed by tvaleriy** 2019-07-01 12:14 UTC
Labels: Bug
