### ISSUE TITLE
error: datepicker is not a function

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#137] opened 2017-09-25 10:14 UTC
This is a

* [x] bug
* [ ] enhancement

Please provide the exact versions of the modules involved (see composer.lock file).
jquery 3.2.1
jquery-ui 1.12.1
spryker/cms                          6.1.3
spryker/cms-gui                      4.2.4 
spryker/gui                          3.9.0

### What you did
calling /cms-gui/edit-page/index?id-cms-page=1

### Actual Behavior
js error "validFrom.datepicker is not a function"

### Expected Behavior
no error

**Comment by tvaleriy** [comment] 2017-09-25 13:24
@AndromedaXP Sorry, but I was unable reproduce this using latest demoshop and two real projects. This is something project-specific probably or there were some issues during setup/deploy (like FE-installing).
If there were no errors, please let us know which version of "spryker/gui" you are using. It was tested with "3.8.0".

**Comment by aurisl** [comment] 2017-09-25 13:50
@tvaleriy  This is valid case when `CmsContentWidget` module is not present. We should fix it for clients without this module.

**Comment by AndromedaXP** [comment] 2017-09-25 13:53
Using
spryker/gui                          3.9.0

I found out that this seems to be a problem with jquery-ui 1.12.1, if I downgrade to 1.10.5 it works fine, can u confirm?

**Comment by tvaleriy** [comment] 2017-09-26 10:30
@AndromedaXP No, I can't confirm this, because it is working fine for me with jquery-ui 1.12.1 as well.

**Comment by AndromedaXP** [comment] 2017-09-26 11:38
That's said to hear. When running ```npm i``` this function is gone in 1.12.1.
Any ideas of side effects which bundles if also have to update or anything else?

**Comment by abelspry** [comment] 2017-10-10 12:49
Hi @AndromedaXP,
I'm sorry for this delay.

I'm checking this issue, and it's really strange that you get to have the v1.12.1. The package.json allows only patch increments (1.10.x) and I really do not know how you got the 1.12. 
There might be a bug somewhere, I'm investigating.

What node/npm versions are you using? Or do you use yarn?
Do you use jquery-ui in project too?

Let me know. 
Thanks.

**Comment by AndromedaXP** [comment] 2017-10-11 15:19
I use node v6.11.3 and npm 3.10.10 and we dont use jquery-ui in project.

After setting up vm again, the problem seems to be gone. Strange.

But thanks for your help, maybe I come back later, when I can reproduce it again.

**Comment by AndromedaXP** [comment] 2017-10-12 07:46
By trying to reproduce the bug I ran into the next problem...

I updated a lot of spryker packages, so I really don't know which is responsible e.g.

spryker/gui                          3.10.0

I clear the node_modules folder before running npm run spy-setup. But it doesn't take the package.json from gui module into account, so I added this to our package.json

    "jquery": "^3.0.0",
    "jquery-migrate": "~3.0.0",
    "jquery-ui": "~1.10.5",

But still the following error when calling ANY backend page :

`spryker-zed-gui-commons.js:12014 Uncaught Error: define cannot be used indirect
    at module.exports (spryker-zed-gui-commons.js:12014)
    at e.migrateVersion (spryker-zed-gui-commons.js:11796)
    at Object.<anonymous> (spryker-zed-gui-commons.js:11797)
    at Object.module.exports (spryker-zed-gui-commons.js:12008)
    at __webpack_require__ (spryker-zed-gui-commons.js:53)
    at Object.<anonymous> (spryker-zed-gui-commons.js:135)
    at __webpack_require__ (spryker-zed-gui-commons.js:53)
    at Object.<anonymous> (spryker-zed-gui-commons.js:105)
    at Object.<anonymous> (spryker-zed-gui-commons.js:115)
    at __webpack_require__ (spryker-zed-gui-commons.js:53)`

**Comment by abelspry** [comment] 2017-10-12 09:09
Hi @AndromedaXP.

Let's see.
This error comes from `jquery-migrate`: they introduced a change that breaks the building chain in webpack.
The solution should be:
- remove "jquery", "jquery-migrate" and "jquery-ui" from your project `package.json` as long as it does not affect Zed (the project `package.json` affects Yves only);
- on you VM, re-run `./setup -i`; it should install the GUI module deps and get the latest version of `oryx-for-zed` (1.1.1) with the fix for your problem.

Let me know.

**Comment by AndromedaXP** [comment] 2017-10-12 10:01
@abelspry What do you mean with `./setup -i` ?

**Comment by AndromedaXP** [comment] 2017-10-13 10:50
Oryx-for-zed will conflict because we still use `"webpack": "^1.13.1"`

I would like to stay on jquery 2.x but the latest gui bundle will not allow me.

Trying to use this workaround does also not work
https://github.com/jquery/jquery-migrate/issues/273#issuecomment-332527584

Sticking to `jquery-migrate 3.0.0` results also in an error
```
spryker-zed-gui-commons.js:75618 Uncaught ReferenceError: DEV is not defined
    at HTMLTableElement.onError (spryker-zed-gui-commons.js:75618)
```

**Comment by abelspry** [comment] 2017-10-17 09:39
OK. I think I need more info then. 
Do you build zed by your own? Because `oryx-for-zed` should not conflict with Yves in any way. 
I'd like to see the webpack configs for Yves and Zed. 
How do you run the setup in VM?
Can you send me the package.json you have in project level?
Which commands do you use to build yves and zed?

**Comment by tvaleriy** [comment] 2017-11-20 10:33
I'm closing this ticket.

**Closed by tvaleriy** 2017-11-20 10:33 UTC
