### ISSUE TITLE
NULL error handling in Storage when product not found

### ISSUE THREAD

**Issue by dantleech** [spryker/support#214] opened 2018-08-06 07:30 UTC
This is a

* [x] bug
* [x] enhancement

```
spryker/product-storage                               1.0.1
```

This is a specific example, but there seem to be many places in the Spryker code where a NULL can be returned and it is not handled. This happens frequently when developing a Spryker application and having a meaningful error message can significantly reduce debugging time and confusion.

### What you did

Visit cart page when a product in the cart is not in storage.

```
https://yves-metro.test/en/cart
```

### Actual Behavior

```
YVES Exception
TypeError - Argument 2 passed to SprykerShop\Yves\CartPage\Mapper\CartItemsAttributeMapper::getAttributesWithAvailability() must be of the type array, null given, called in /app/vendor/spryker-shop/cart-page/src/SprykerShop/Yves/CartPage/Mapper/CartItemsAttributeMapper.php on line 64
in /app/vendor/spryker-shop/cart-page/src/SprykerShop/Yves/CartPage/Mapper/CartItemsAttributeMapper.php (78)
```

### Expected Behavior

An exception for example:

```
Could not find product by key "kv:product_abstract..."
```

**Comment by tvaleriy** [comment] 2018-08-06 08:59
Thank you for the bug report. Yes, you are right and we have a plan how we can improve ourselves here.
I will notify when this particular issue is fixed and released.

**Comment by tvaleriy** [comment] 2018-10-30 13:35
@dantleech We can't reproduce this with spryker/product-storage 1.3.1. Is it possible for you to update to this version?

**Comment by tvaleriy** [comment] 2019-02-12 15:51
I'm closing this ticket. But feel free to contact us as soon as you have question.

**Closed by tvaleriy** 2019-02-12 15:51 UTC
Labels: waiting for customer feedback
