### ISSUE TITLE
Collector throws exception when redirect is deleted

### ISSUE THREAD

**Issue by KaiCMueller** [spryker/support#94] opened 2016-12-20 12:35 UTC
This is a

* [x] bug
* [ ] enhancement

### What you did

1. Login to ZED and create a cms/redirect from URL x to URL y
2. Execute collector:storage:export on console
3. Delete the redirect entry
4. Create the same redirect from URL x to URL y again
5. Execute collector:storage:export on console

### Actual Behavior

**Export process throws Exception:**
Duplicate entry '123-de.de_de.url./url' for key 'spy_touch_storage-unique-fk_locale'
Executed query: 
```
INSERT INTO `spy_touch_storage` (`id_touch_storage`, `fk_locale`, `fk_touch`, `key`) VALUES (NULL, 46, 36726, '123-de.de_de.url./url')
```
in /data/shop/development/current/src/Orm/Zed/Touch/Persistence/Base/SpyTouchStorage.php (776)

### Expected Behavior

When the URL is deleted, the matching touch storage entry should be deleted too. It seems this behavior was removed in Collector Bundle v. 3.0.0.

**Comment by dereuromark** [comment] 2016-12-22 09:36
What Cms version are you using?

Were you able to reproduce this with the current demoshop and Collector 4.0?
We cannot reproduce it there. Looks like this is fixed with the current head of bundle versions.

**Comment by KaiCMueller** [comment] 2016-12-22 09:55
CMS @ 2.1.0
Collector @ 3.1.1

**Comment by KaiCMueller** [comment] 2016-12-22 09:56
I forgot one point in the "What you did" listing and added it now. Please try again to reproduce.

**Comment by dereuromark** [comment] 2016-12-22 16:05
You can either upgrade to the new collector major 4.x or we can deliver you a patch for the 3.x version.
Please see the following hotfix branch:
https://github.com/spryker/Collector/tree/hotfix/core-757-abstract-touch-updater-fix

If you enable that one for your composer.json for now, you should be able to confirm us that this would indeed fix your issue. You can also keep that then until we released a patch.

**Comment by dereuromark** [comment] 2016-12-29 09:36
This has been patch released as https://github.com/spryker/Collector/releases/tag/3.1.4 now.

**Closed by dereuromark** 2016-12-29 09:36 UTC
Labels: Bug, high prio
