### ISSUE TITLE
user group listing is dupicated

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#261] opened 2018-12-21 09:54 UTC
This is a

* [x] bug
* [ ] enhancement

spryker/acl                             3.1.2
spryker/gui                             3.16.1
spryker/agent-gui                       1.0.0

### What you did
Calling /acl/group in ZED will show a listing of user groups which are listed 3-times instead of once.
See Screenshot attached

![image](https://user-images.githubusercontent.com/12390718/50336374-537ea300-050e-11e9-9ae0-2b0ee205edd1.png)

**Comment by anastasia-chistokhvalova** [comment] 2018-12-21 10:45
Hi @AndromedaXP,

that looks weird, could you please make sure that it is not a cache issue and also please check that latest installation of frontend didn't throw any errors? 

could you please also tell me what env. are you working on?  (b2b-demo-shop or some other)?

**Comment by AndromedaXP** [comment] 2018-12-28 11:05
Cache was cleared, Frontend build without errors, we started with demoshop 3 years ago, so probably not much left of it

**Comment by tvaleriy** [comment] 2019-01-08 10:37
Hi @AndromedaXP, probably this is something project related as we can't confirm the issue on our side. I'm closing this, but feel free to raise it again if you insist that the issue is on our side.

**Closed by tvaleriy** 2019-01-08 10:37 UTC
