### ISSUE TITLE
EmptyAllCachesConsole doesn't return correct Error_Code

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#255] opened 2018-12-11 11:19 UTC
This is a

* [x] bug
* [ ] enhancement

spryker/cache                           3.1.0

### What you did
Running `cache:empty-all` can result in an Exception e.g. missing rights or IOException when "Directory not empty". The command should catch these and return the correct `self::CODE_ERROR` so that deployment can fail when command runs into exception.

### Actual Behavior
Exception is thrown, but deployment doesn't recognize it.

**Comment by tvaleriy** [comment] 2018-12-11 13:12
Thank you for the report. I will notify when it is fixed and released.

**Comment by m7moud** [comment] 2019-06-14 14:07
Hi @AndromedaXP 

I think this was an issue in Symfony's release `v3.4.16` was fixed and released in the release `v3.4.17`: https://github.com/symfony/symfony/pull/28664

Can you confirm what `symfony/console` do you have in your `composer.lock` file.

**Comment by AndromedaXP** [comment] 2019-06-14 17:27
You got something wrong here...
We use symfony/console  v3.4.24 but the problem is not on symfony side its in spryker's console command EmptyAllCachesConsole that the execute method doesn't return a status code at all.
And this brought us into trouble when deployment doesn't fail when this command fails but no error code is send.

**Comment by m7moud** [comment] 2019-06-17 12:34
Hi again,

I think you will need to be more specific on how do you use this command, or how can we reproduce your issue exactly.

By default Symfony's console commands return 0 if the command returns null, which is the code for everything is fine.

... also by default on any exception, it will return the exception error code if it's numeric and if it's not zero, and by default it will return `1` https://github.com/symfony/console/blob/v3.4.24/Application.php#L156

**Comment by AndromedaXP** [comment] 2019-06-17 13:17
The code line you send is not reachable as in Line 150 the exception is not cached because `$this->catchException` is set to false here https://github.com/spryker/console/blob/409bceb809991b28c5a460c9673c353f57e59452/src/Spryker/Zed/Console/Communication/ConsoleBootstrap.php#L41

**Comment by m7moud** [comment] 2019-06-28 10:52
Hi @AndromedaXP 

Thanks for the tip, I think I figured the issue.

If `setCatchExceptions` was set to `false`, the console commands return code, will be `self::CODE_SUCCESS` for success and ranges from `1` (`self::CODE_ERROR`) to infinity for errors, because it will return the exception code for errors and not always `self::CODE_ERROR`. 

While if `setCatchExceptions` was set to `true`, the return code will always be binary, `self::CODE_SUCCESS`   for success as it's always and only `self::CODE_ERROR` for errors.

A helpful tip: You can check for errors as the negation of success instead, like `!self::CODE_SUCCESS`   in your deployment script instead of checking for `self::CODE_ERROR`, this should for your use case I guess, or alternatively an improvement with a configurable console exceptions handling should be released soon.

Please let's up know if this helpful and we will keep you updated.

**Comment by tvaleriy** [comment] 2019-07-03 14:00
Hi @AndromedaXP,
this should have been fixed in https://github.com/spryker/console/releases/tag/4.2.0.

Best,
Spryker Support Team

**Closed by tvaleriy** 2019-07-03 14:00 UTC
Labels: Bug, waiting for customer feedback
