### ISSUE TITLE
Navigation using the bundle navigation config does not work.

### ISSUE THREAD

**Issue by vmigel** [spryker/support#108] opened 2017-03-14 09:06 UTC
This is a

* [x] bug
* [ ] enhancement

For questions please consult the [Spryker Forum](http://discuss.spryker.com/).

```
    "spryker/acl": "^3.0.0",
    "spryker/application": "^3.0.0",
    "spryker/assertion": "^3.0.0",
    "spryker/auth": "^3.0.0",
    "spryker/auth-mail-connector": "^3.0.0",
    "spryker/availability": "^5.0.0",
    "spryker/availability-cart-connector": "^4.0.0",
    "spryker/availability-gui": "^2.0.0",
    "spryker/braintree": "^0.5.0",
    "spryker/cache": "^3.0.0",
    "spryker/calculation": "^3.0.0",
    "spryker/cart": "^3.0.0",
    "spryker/catalog": "^5.0.0",
    "spryker/category": "^3.0.0",
    "spryker/category-exporter": "^3.0.0",
    "spryker/checkout": "^3.0.0",
    "spryker/cms": "^4.0.0",
    "spryker/cms-gui": "^2.0.0",
    "spryker/collector": "^5.0.0",
    "spryker/collector-search-connector": "^1.0.0",
    "spryker/collector-storage-connector": "^1.0.0",
    "spryker/config": "^3.0.0",
    "spryker/console": "^3.0.0",
    "spryker/country": "^3.0.0",
    "spryker/csv": "^2.0.0",
    "spryker/currency": "^2.0.0",
    "spryker/customer": "^4.0.0",
    "spryker/customer-group": "^2.0.0",
    "spryker/customer-group-discount-connector": "^2.0.0",
    "spryker/development": "^3.0.0",
    "spryker/discount": "^4.0.0",
    "spryker/discount-calculation-connector": "^4.0.0",
    "spryker/discount-sales-aggregator-connector": "^3.0.0",
    "spryker/dummy-payment": "^2.0.0",
    "spryker/elastica": "^3.0.0",
    "spryker/error-handler": "^2.0.0",
    "spryker/event-journal": "^3.0.0",
    "spryker/glossary": "^3.0.0",
    "spryker/graph": "^3.0.0",
    "spryker/graphviz": "^2.0.0",
    "spryker/gui": "^3.0.0",
    "spryker/guzzle": "^2.0.0",
    "spryker/heartbeat": "^3.0.0",
    "spryker/installer": "^4.0.0",
    "spryker/invoice": "^2.0.0",
    "spryker/kernel": "^3.0.0",
    "spryker/key-builder": "^1.0.0",
    "spryker/locale": "^3.0.0",
    "spryker/log": "^3.0.0",
    "spryker/mail": "^4.0.0",
    "spryker/maintenance": "^3.0.0",
    "spryker/mandrill": "^2.0.0",
    "spryker/messenger": "^3.0.0",
    "spryker/money": "^2.0.0",
    "spryker/monolog": "^2.0.0",
    "spryker/new-relic": "^3.0.0",
    "spryker/new-relic-api": "^1.0.0",
    "spryker/newsletter": "^4.0.0",
    "spryker/nopayment": "^3.0.0",
    "spryker/oms": "^6.0.0",
    "spryker/oms-discount-connector": "^3.0.0",
    "spryker/payment": "^3.0.0",
    "spryker/payolution": "^3.0.0",
    "spryker/payone": "^4.0.0",
    "spryker/pimple": "^2.0.0",
    "spryker/price": "^4.0.0",
    "spryker/price-cart-connector": "^3.0.0",
    "spryker/product": "^5.0.0",
    "spryker/product-bundle": "^2.0.0",
    "spryker/product-cart-connector": "^4.0.0",
    "spryker/product-category": "^4.0.0",
    "spryker/product-discount-connector": "^3.0.0",
    "spryker/product-image": "^3.0.0",
    "spryker/product-management": "^0.3.0",
    "spryker/product-option": "^4.0.0",
    "spryker/product-option-cart-connector": "^4.0.0",
    "spryker/product-option-discount-connector": "^4.0.0",
    "spryker/product-search": "^5.0.0",
    "spryker/propel": "^3.0.0",
    "spryker/propel-orm": "^1.0.0",
    "spryker/queue": "^0.2.0",
    "spryker/quote": "^1.0.0",
    "spryker/redis": "^2.0.0",
    "spryker/refund": "^4.0.0",
    "spryker/sales": "^5.0.0",
    "spryker/sales-aggregator": "^4.0.0",
    "spryker/sales-split": "^3.0.0",
    "spryker/search": "^6.0.0",
    "spryker/sequence-number": "^3.0.0",
    "spryker/session": "^3.0.0",
    "spryker/setup": "^3.0.0",
    "spryker/shipment": "^4.0.0",
    "spryker/silex": "^2.0.0",
    "spryker/sql-criteria-builder": "^1.0.0",
    "spryker/state-machine": "^2.0.0",
    "spryker/step-engine": "^2.0.0",
    "spryker/stock": "^4.0.0",
    "spryker/stock-sales-connector": "^3.0.0",
    "spryker/storage": "^3.0.0",
    "spryker/symfony": "^3.0.0",
    "spryker/tax": "^4.0.0",
    "spryker/tax-product-connector": "^4.0.0",
    "spryker/testify": "^3.0.0",
    "spryker/touch": "^3.0.0",
    "spryker/transfer": "^3.0.0",
    "spryker/twig": "^3.0.0",
    "spryker/url": "^3.0.0",
    "spryker/user": "^3.0.0",
    "spryker/wishlist": "^4.0.0",
    "spryker/zed-navigation": "^1.0.0",
    "spryker/zed-request": "^3.0.0",
    "spryker/zend": "^2.0.0",
```

### What you did
I went through documentation [2. Add navigation using the bundle navigation config](http://spryker.github.io/tutorials/zed/add-navigation/#2--add-navigation-using-the-bundle-navigation-config) and found that Spryker does not work properly. It looks that `vendor/bin/console application:build-navigation-cache` works well only for bundle navigations from vendor folder but not for bundle navigation from Pyz folder.

### Actual Behavior
I see Exception
```
Whoops \ Exception \ ErrorException (E_NOTICE)
Undefined index: bundle
```

### Expected Behavior
I should see new menu element

**Comment by dereuromark** [comment] 2017-04-10 09:25
Duplicate of https://github.com/spryker/support/issues/100

**Closed by dereuromark** 2017-04-10 09:25 UTC
