### ISSUE TITLE
Flysystem implementation placed wrong in demoshop.

### ISSUE THREAD

**Issue by diabolus** [spryker/support#207] opened 2018-06-11 09:33 UTC
This is a

* [x] bug
* [ ] enhancement

For questions please consult the [Spryker Forum](http://discuss.spryker.com/).

Please provide the exact versions of the modules involved (see composer.lock file).
https://github.com/spryker/demoshop  v2.32  

### What you did

This bug comes with demoshop. ```Flysystem``` implementation placed wrong under ```Pyz\Zed\Flysystem``` namespace. 

### Actual Behavior

```/src/Pyz/Zed/Flysystem/FlysystemDependencyProvider.php``` not loading due to wrong location. ```Flysystem``` is defined as a service now and Spryker looking the directory under Service directory and skipping the given provider under Zed and finally getting the dependencies from vendor. 

### Expected Behavior

```/src/Pyz/Zed/Flysystem/``` directory should move to the ```/src/Pyz/Service/Flysystem/``` and namespaces should be updated.

**Comment by tvaleriy** [comment] 2018-06-12 09:49
Thank you for the feedback. The issue is in our backlog now and I will notify when it is fixed and released.

**Comment by tvaleriy** [comment] 2018-11-26 11:10
This was fixed in the master branch.

**Closed by tvaleriy** 2018-11-26 11:10 UTC
Labels: Bug
