### ISSUE TITLE
[BUG] spryker/customer: Update password using updateCustomer critical broken

### ISSUE THREAD

**Issue by vollbio** [spryker/support#219] opened 2018-08-22 10:49 UTC
Please provide the exact versions of the modules involved (see composer.lock file).
**spryker/customer: 7.10.0**

### What you did
I created a test to make so my rewrite does not brake core functionality. I wrote a test to change password using the _updateCustomer_ facade method. See test: https://pastebin.com/m5DjwdZH

What I see the issue is cloning the _$customerTransfer_ before passing to _updatePassword_ method, which replaces the plain text password with the hash.

This is rather critical as it potentially exposes plain passwords in case of persistent storage exposure.

### Actual Behavior
* The plain password (and optionally other attributes) is persisted.
* The customer can not login with the new password.

### Expected Behavior
* The hashed password (and optionally other attributes) is persisted.
* The customer can login with the new password.

**Comment by tvaleriy** [comment] 2018-08-22 13:48
Thank you for the feedback. I will notify when it is changed and released.

**Comment by gerner-spryker** [comment] 2018-09-20 08:05
Hello Robert,

Thank you for the bug report. We did check the issue and the current behaviour was clarified in the method's specification to reduce unexpected behaviour. However, since currently this method allows everyone to either send the unencrypted password through the `newPassword` field or send a custom encrypted password through the `password` field, removing 1 of these would cause a `major` impact. Due this facade method might open up security questions when wrongly used, we will definitely re-consider this internally upon the next `major` version of the `customer` module.

Best,
Karoly

**Comment by tvaleriy** [comment] 2020-04-24 18:39
Hi @vollbio,
this should have been fixed in https://github.com/spryker/customer/releases/tag/7.26.9.

Best,
Spryker Support Team

**Closed by tvaleriy** 2020-04-24 18:39 UTC
Labels: Bug, Waiting for the next major version
